### ISSUE TITLE
错误的包名+修改How-to-use_CN

### ISSUE THREAD

**Issue by paperbab** [PILIHU2022/My-dotfiles#2]
在programs.md中
`WM:Hyprland-git <sup>AUR</sup>`应当改为`WM:hyprland-git <sup>AUR</sup>`
`Editor:Neovim<sup>包</sup>有`应当改为`Editor:neovim<sup>包</sup>有`
`pipewire-jac   :jack 客户端启动支持\`应当改为`pipewire-jack   :jack 客户端启动支持\`

在How-to-use_CN.md里的“若你想使用全局黑暗模式”，应该指向How-to-set-dark-mode.md 
正在提交PR

**Comment by PILIHU2022** [comment]
好的，感谢你。也让我发现了一些问题

**Comment by paperbab** [comment]
#3 可以通过下，顺便刷下勋章
